name: Work 1 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Something
      run: echo "Hola Pitaya!"
      smtp.gmail.com://juanpb.iteso@gmail.com:pswn yxue znyp fvir:smtp.gmail.com:587